// Copyright (C) 2025 Samuel Zormeister, All rights reserved. Licensed under the BSD-3 Clause License.

#ifndef __PLATFORM_SMBIOS_TYPES_PROCESSORINFO_H__
#define __PLATFORM_SMBIOS_TYPES_PROCESSORINFO_H__

#include <platform/smbios/types/entry_point.h>
#include <platform/smbios/types/header.h>

typedef enum {
    SMBIOS_PROCESSOR_TYPE_OTHER = 0x1,
    SMBIOS_PROCESSOR_TYPE_UNKNOWN = 0x2,
    SMBIOS_PROCESSOR_TYPE_CENTRAL_PROCESSOR = 0x3,
    SMBIOS_PROCESSOR_TYPE_MATH_PROCESSOR = 0x4,
    SMBIOS_PROCESSOR_TYPE_DSP_PROCESSOR = 0x5,
    SMBIOS_PROCESSOR_TYPE_VIDEO_PROCESSOR = 0x6,
} smbios_processor_type_t;

// this enum was referenced from SMBIOS v3.8.0
// please update when necessary
typedef enum {
    SMBIOS_PROCESSOR_FAMILY_OTHER = 0x1,
    SMBIOS_PROCESSOR_FAMILY_UNKNOWN = 0x2,

    // legacy intel i presume.
    SMBIOS_PROCESSOR_FAMILY_8086,
    SMBIOS_PROCESSOR_FAMILY_80286,
    SMBIOS_PROCESSOR_FAMILY_I386,
    SMBIOS_PROCESSOR_FAMILY_I486,
    SMBIOS_PROCESSOR_FAMILY_8087,
    SMBIOS_PROCESSOR_FAMILY_80287,
    SMBIOS_PROCESSOR_FAMILY_80387,
    SMBIOS_PROCESSOR_FAMILY_80487,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM_PRO,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM_II,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM_WITH_MMX,
    SMBIOS_PROCESSOR_FAMILY_CELERON,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM_II_XEON,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM_III,
    SMBIOS_PROCESSOR_FAMILY_M1,
    SMBIOS_PROCESSOR_FAMILY_M2,
    SMBIOS_PROCESSOR_FAMILY_CELERON_M,
    SMBIOS_PROCESSOR_FAMILY_PENTIUM_IV_HT,

    SMBIOS_PROCESSOR_FAMILY_DURON = 0x18,
    SMBIOS_PROCESSOR_FAMILY_K5,
    SMBIOS_PROCESSOR_FAMILY_K6,
    SMBIOS_PROCESSOR_FAMILY_K6_2,
    SMBIOS_PROCESSOR_FAMILY_K6_3,
    SMBIOS_PROCESSOR_FAMILY_ATHLON,
} smbios_processor_family_t;

typedef struct {
    smbios_table_header_t header;
    smbios_string_t socket_name; // 'FP6'

} smbios_processor_info_t;

#endif /* __PLATFORM_SMBIOS_TYPES_PROCESSORINFO_H__ */
