// Copyright (C) 2024-2025 Samuel Zormeister, All rights reserved. Licensed under the BSD-3 Clause License.

#ifndef __PLATFORM_EFI_TYPES_STATUS_H__
#define __PLATFORM_EFI_TYPES_STATUS_H__

#include <lib/types.h>

typedef uintn_t efi_status_t;

#define EFI_HIGH_BIT (1 << (TARGET_CPU_ADDRESS_WIDTH-1))

#define EFI_ERROR_CODE(code) (EFI_HIGH_BIT | (code))

/* keep it similar to EDK II's definitions */
#define EFI_ERROR(code) (code & EFI_HIGH_BIT)

enum EFI_STATUS_CODES {
    EFI_SUCCESS = 0,
    EFI_LOAD_ERROR = EFI_ERROR_CODE(1),
    EFI_INVALID_PARAMETER = EFI_ERROR_CODE(2),
    EFI_UNSUPPORTED = EFI_ERROR_CODE(3),
    EFI_BAD_BUFFER_SIZE = EFI_ERROR_CODE(4),
    EFI_BUFFER_TOO_SMALL = EFI_ERROR_CODE(5),
    EFI_NOT_READY = EFI_ERROR_CODE(6),
    EFI_DEVICE_ERROR = EFI_ERROR_CODE(7),
    EFI_WRITE_PROTECTED = EFI_ERROR_CODE(8),
    EFI_OUT_OF_RESOURCES = EFI_ERROR_CODE(9),
    EFI_VOLUME_CORRUPTED = EFI_ERROR_CODE(10),
    EFI_VOLUME_FULL = EFI_ERROR_CODE(11),
    EFI_NO_MEDIA = EFI_ERROR_CODE(12),
    EFI_MEDIA_CHANGED = EFI_ERROR_CODE(13),
    EFI_NOT_FOUND = EFI_ERROR_CODE(14),
    EFI_ACCESS_DENIED = EFI_ERROR_CODE(15),
    EFI_NO_RESPONSE = EFI_ERROR_CODE(16),
    EFI_NO_MAPPING = EFI_ERROR_CODE(17),
    EFI_TIMEOUT = EFI_ERROR_CODE(18),
    EFI_NOT_STARTED = EFI_ERROR_CODE(19),
    EFI_ALREADY_STARTED = EFI_ERROR_CODE(20),
    EFI_ABORTED = EFI_ERROR_CODE(21),
    EFI_ICMP_ERROR = EFI_ERROR_CODE(22),
    EFI_TFTP_ERROR = EFI_ERROR_CODE(23),
    EFI_PROTOCOL_ERROR = EFI_ERROR_CODE(24),
    EFI_INCOMPATIBLE_VERSION = EFI_ERROR_CODE(25),
    EFI_SECURITY_VIOLATION = EFI_ERROR_CODE(26),
    EFI_CRC_ERROR = EFI_ERROR_CODE(27),
    EFI_END_OF_MEDIA = EFI_ERROR_CODE(28),
    EFI_END_OF_FILE = EFI_ERROR_CODE(31),
    EFI_INVALID_LANGUAGE = EFI_ERROR_CODE(32),
    EFI_COMPROMISED_DATA = EFI_ERROR_CODE(33),
    EFI_IP_ADDRESS_CONFLICT = EFI_ERROR_CODE(34),
    EFI_HTTP_ERROR = EFI_ERROR_CODE(35),
    EFI_WARN_UNKNOWN_GLYPH = 1,
    EFI_WARN_DELETE_FAILURE = 2,
    EFI_WARN_WRITE_FAILURE = 3,
    EFI_WARN_BUFFER_TOO_SMALL = 4,
    EFI_WARN_STALE_DATA = 5,
    EFI_WARN_FILE_SYSTEM = 6,
    EFI_WARN_RESET_REQUIRED = 7,
};

#endif /* __PLATFORM_EFI_TYPES_STATUS_H__ */
